### ISSUE TITLE
Master branch fails to build on Linux

### ISSUE THREAD

**Issue by nickgirga** [dashodanger/EDGE-classic#141]
The 1.1 tag builds fine on Linux, but the master branch does not. I looked into why this is happening. Here's my make log for the failing git build: [make.log](https://github.com/dashodanger/EDGE-classic/files/8972166/make.log)

In the last few lines, I noticed that it said:
```
.../source_files/edge/umapinfo.cc:399:22: error: 'stricmp' was not declared in this scope; did you mean ‘strncmp’?
```
So, I just looked up "stricmp linux" (thinking maybe I need to install a dependency or something) and I see a lot of people with the same "not declared" problem. I think this is what is causing the issue. `stricmp` is [apparently not POSIX](https://stackoverflow.com/a/1784777).

**Comment by dashodanger** [comment]
Thanks for the report; it should be fixed with commit https://github.com/dashodanger/EDGE-classic/commit/6b3f6abc9272b701b5923a6c53f5878e8d1f02ae, which added the necessary EPI header that redefines things like stricmp to OS-compatible functions, in this case strcasecmp for Linux. It seems to work on my local VM, but I'll leave this open until you get a chance to check. You'll want to sync with the latest commit, though, as I had to fix some stuff in e_main.cc that Linux didn't like either.

**Comment by nickgirga** [comment]
Oh wow that was a really quick response! And the fix works great. Everything is working as expected now on the master branch. Thanks a ton!
