### ISSUE TITLE
priorities for chosen IWAD

### ISSUE THREAD

**Issue by andwj** [dashodanger/EDGE-classic#190]
This is not a major thing, but I think when searching for an IWAD to load, certain ones should be preferred, in particular DOOM2.WAD since most mods tend to use that IWAD as their base and may fail with DOOM.WAD (etc).

So instead of stopping at the first usable IWAD, give each one a score based on their name and pick the highest score.  I suggest "DOOM2" should have the highest score, then maybe "FREEDOOM2" since it is highly compatible with it, then "TNT" and "PLUTONIA", etc...

**Comment by dashodanger** [comment]
That does make sense; I think I can probably massage the iwad_unique_lumps into a map or somesuch that stores a score value in addition to the lumps it's checking for, or maybe make a struct with both the score and lump array within it and then have an array of such structs.

**Comment by dashodanger** [comment]
I just pushed https://github.com/dashodanger/EDGE-classic/commit/fb692a15df9061fffbd7d520e0ebd592511c5e48 to test the new system. A summary of the scoring preferences (copied from the CHANGELOG):

+ If no -iwad parameter is given, an IWAD will be selected from all IWADs discovered in default search paths based on a scoring/preference system
  - Doom 2/Freedoom Phase 2/Final Doom are highest priority due to highest compatibilty with mods/PWADs
  - Doom 1/Freedoom Phase 1 are second in line
  - Remaining Doom-based IWADs (HacX/Harmony for now) are third
  - Heretic/Blasphemer, being the newest games supported, are after those
  - If a new custom standalone IWAD (with EDGEIWAD lump) is present in the search list, it will be considered last

**Comment by andwj** [comment]
Worked like a charm, cheers!

**Comment by dashodanger** [comment]
Awesome, thanks for checking. I'll go ahead and close it out then.
